export const envKeys = {
	ENV: 'ENV',
	PORT: 'PORT',
	DB: {
		DEFAULT_URI: 'DB_DEFAULT_URI',
		SUB_URI: 'DB_SUB_URI',
	},
	SECURITY: {
		HASH_ROUNDS: 'HASH_ROUNDS',
		ACCESS_TOKEN_SECRET: 'ACCESS_TOKEN_SECRET',
		REFRESH_TOKEN_SECRET: 'REFRESH_TOKEN_SECRET',
	},
	CLIENT: {
		LOCAL: 'CLIENT_LOCAL_URL',
		PROD: 'CLIENT_PROD_URL',
	},
	MAILER: {
		HOST: 'MAILER_HOST',
		PORT: 'MAILER_PORT',
		USER: 'MAILER_USER',
		PASS: 'MAILER_PASS',
	},
};
