import * as Joi from 'joi';

export const envValidationSchema = Joi.object({
	ENV: Joi.string().valid('dev', 'prod').default('dev'),
	PORT: Joi.number().default(3000),
	DB_DEFAULT_URI: Joi.string().required(),
	DB_SUB_URI: Joi.string().required(),
	ACCESS_TOKEN_SECRET: Joi.string().required(),
	REFRESH_TOKEN_SECRET: Joi.string().required(),
	INVITE_TOKEN_SECRET: Joi.string().required(),
	CLIENT_LOCAL_URL: Joi.string().default('http://localhost:3000'),
	CLIENT_PROD_URL: Joi.string(),
	MAILER_HOST: Joi.string(),
	MAILER_PORT: Joi.number(),
	MAILER_USER: Joi.string(),
	MAILER_PASS: Joi.string(),
	HASH_ROUNDS: Joi.number(),
	CLOUDFLARE_R2_ACCESS_KEY: Joi.string(),
	CLOUDFLARE_R2_SECRET_KEY: Joi.string(),
	CLOUDFLARE_R2_ENDPOINT: Joi.string(),
	CLOUDFLARE_R2_BUCKET: Joi.string(),
	CLOUDFLARE_R2_REGION: Joi.string(),
	CLOUDFLARE_R2_PUBLIC_URL: Joi.string(),
	GITHUB_CLIENT_ID: Joi.string(),
	GITHUB_CLIENT_SECRET: Joi.string(),
	GEMINI_API_URL: Joi.string(),
	GEMINI_API_KEY: Joi.string(),
});
