export const envKeys = {
	ENV: 'ENV',
	PORT: 'PORT',
	DB: {
		DEFAULT_URI: 'DB_DEFAULT_URI',
		SUB_URI: 'DB_SUB_URI',
	},
	SECURITY: {
		HASH_ROUNDS: 'HASH_ROUNDS',
		ACCESS_TOKEN_SECRET: 'ACCESS_TOKEN_SECRET',
		REFRESH_TOKEN_SECRET: 'REFRESH_TOKEN_SECRET',
		INVITE_TOKEN_SECRET: 'INVITE_TOKEN_SECRET',
	},
	CLIENT: {
		LOCAL: 'CLIENT_LOCAL_URL',
		PROD: 'CLIENT_PROD_URL',
	},
	MAILER: {
		HOST: 'MAILER_HOST',
		PORT: 'MAILER_PORT',
		USER: 'MAILER_USER',
		PASS: 'MAILER_PASS',
	},
	CLOUDFLARE: {
		ACCESS_KEY: 'CLOUDFLARE_R2_ACCESS_KEY',
		SECRET_KEY: 'CLOUDFLARE_R2_SECRET_KEY',
		ENDPOINT: 'CLOUDFLARE_R2_ENDPOINT',
		BUCKET: 'CLOUDFLARE_R2_BUCKET',
		REGION: 'CLOUDFLARE_R2_REGION',
		PUBLIC_URL: 'CLOUDFLARE_R2_PUBLIC_URL',
	},
	OAUTH: {
		GITHUB: {
			ID: 'OAUTH_GITHUB_CLIENT_ID',
			SECRET: 'OAUTH_GITHUB_CLIENT_SECRET',
		},
	},
	AI: {
		GEMINI: {
			KEY: 'GEMINI_API_KEY',
			URL: 'GEMINI_API_URL',
		},
	},
};
