name: Deploy to cloudtype
on:
    push:
        branches:
            - develop
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Connect deploy key
              uses: cloudtype-github-actions/connect@v1
              with:
                  token: ${{ secrets.CLOUDTYPE_TOKEN }}
                  ghtoken: ${{ secrets.GHP_TOKEN }}
            - name: Deploy
              uses: cloudtype-github-actions/deploy@v1
              with:
                  token: ${{ secrets.CLOUDTYPE_TOKEN }}
                  project: kkoor521/quizbank
                  stage: main
                  yaml: |
                      name: quizbank-be
                      app: node@22
                      options:
                        env:
                          - name: ENV
                            secret: ENV
                          - name: PORT
                            secret: PORT
                          - name: DB_DEFAULT_URI
                            secret: DB_DEFAULT_URI
                          - name: DB_SUB_URI
                            secret: DB_SUB_URI
                          - name: ACCESS_TOKEN_SECRET
                            secret: ACCESS_TOKEN_SECRET
                          - name: REFRESH_TOKEN_SECRET
                            secret: REFRESH_TOKEN_SECRET
                          - name: HASH_ROUNDS
                            secret: HASH_ROUNDS
                          - name: MAILER_HOST
                            secret: MAILER_HOST
                          - name: MAILER_PORT
                            secret: MAILER_PORT
                          - name: MAILER_USER
                            secret: MAILER_USER
                          - name: MAILER_PASS
                            secret: MAILER_PASS
                          - name: INVITE_TOKEN_SECRET
                            secret: INVITE_TOKEN_SECRET
                          - name: CLOUDFLARE_R2_ACCESS_KEY
                            secret: CLOUDFLARE_R2_ACCESS_KEY
                          - name: CLOUDFLARE_R2_SECRET_KEY
                            secret: CLOUDFLARE_R2_SECRET_KEY
                          - name: CLOUDFLARE_R2_ENDPOINT
                            secret: CLOUDFLARE_R2_ENDPOINT
                          - name: CLOUDFLARE_R2_BUCKET
                            secret: CLOUDFLARE_R2_BUCKET
                          - name: CLOUDFLARE_R2_REGION
                            secret: CLOUDFLARE_R2_REGION
                          - name: CLOUDFLARE_R2_PUBLIC_URL
                            secret: CLOUDFLARE_R2_PUBLIC_URL
                          - name: OAUTH_GITHUB_CLIENT_ID
                            secret: OAUTH_GITHUB_CLIENT_ID
                          - name: OAUTH_GITHUB_CLIENT_SECRET
                            secret: OAUTH_GITHUB_CLIENT_SECRET
                          - name: GEMINI_API_URL
                            secret: GEMINI_API_URL
                          - name: GEMINI_API_KEY
                            secret: GEMINI_API_KEY
                          - name: RESET_PASSWORD_TOKEN_SECRET
                            secret: RESET_PASSWORD_TOKEN_SECRET
                          - name: CLIENT_PROD_URL
                            secret: CLIENT_PROD_URL
                        ports: 3000
                        build: pnpm build
                        start: pnpm start:prod
                        install: pnpm i
                        buildenv: []
                      context:
                        git:
                          url: git@github.com:${{ github.repository }}.git
                          ref: ${{ github.ref }}
                        preset: nest.js
